### ISSUE TITLE
composer install for private repositories 

### ISSUE THREAD

**Issue by jeysaravana** [xwp/vip-go-site#115]
I don't see documentation for how to install github private repositories. is there any way to do that?

**Comment by kasparsd** [comment]
@jeysaravana Composer can use Git and its authentication system for pulling down private packages as described here https://getcomposer.org/doc/articles/handling-private-packages.md

So something like this in your `composer.json` should work:

```json
{
  "name": "your/vip-go-site",
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    },
    {
      "type": "git",
      "url": "git@github.com:example-vendor/package-repo.git"
    }
  ],
  "require": {
    "example-vendor/package-repo": "1.2.3"
  }
}
```

**Comment by jeysaravana** [comment]
@kasparsd thanks for the instant reply. I want to use that in VIP as well. How it will handle the authentication. So I won't commit my plugins to the repo.

**Comment by kasparsd** [comment]
@jeysaravana Oh, so would like to have your CI/CD pipeline deploy the code to VIP, including those private dependencies, right?

Ideally, you would create a new GitHub "machine user" which is then given read access to the private dependency repository and "write" access to the VIP Go upstream repository. You would then need to create a new GitHub token (or SSH key) for that machine user which can then be used to act as that machine user from any computer that has access to that token.

Finally, you need to feed that token to the CI/CD process and this depends on the CI/CD service you're using. With GitHub actions this can be done using secrets during the [`checkout` action](https://github.com/actions/checkout). On Travis it would be easier to use a dedicated SSH key associated with the machine user which is then used by the Travis runner https://docs.travis-ci.com/user/private-dependencies/#user-key

This VIP site template defaults to using Travis and the SSH key pair to do the authentication as the machine user.

**Comment by jeysaravana** [comment]
@kasparsd ,
yes. that's what I was looking. thanks much for your info. I thought VIP will have Travis. but now I see that we need to setup that.
