### ISSUE TITLE
Homebrew deprecated command

### ISSUE THREAD

**Issue by nandotess** [xwp/vip-go-site#117]
On the documentation where it says to run the command `brew cask install docker`, it's actually `brew install --cask docker` if you have the most updated version of Homebrew... based on this thread:

https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364

> `brew cask <command>` was deprecated in favor of `brew <command> --cask` in **Homebrew 2.6.0**. Now that **2.7.0** has been released, they have been disabled.

So depending on the version of your Homebrew, this command might fail as it happened to me.

**Comment by kasparsd** [comment]
This is a great suggestion @nandotess! Can you please open a pull request to address this? Should we also add a note saying that `brew cask install` is necessary if using Homebrew before version 2.6.0 or can we just assume that people would be running the latest versions of the suggested software?

**Comment by nandotess** [comment]
@kasparsd maybe it's better to give both options, depending on the Homebrew version. I will create the PR, thank you!

**Comment by kasparsd** [comment]
Fixed in #121.
