### ISSUE TITLE
Update file location on the README (documentation)

### ISSUE THREAD

**Issue by nandotess** [xwp/vip-go-site#118]
On the documentation where it says **with the configuration from local/wp-cli.yml**, it's actually **with the configuration from local/public/wp-cli.yml** (the file location needs to be updated/fixed).

**Comment by kasparsd** [comment]
That's a great find! Indeed, the file path has now changed:

https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/local/public/wp-cli.yml

**Comment by nandotess** [comment]
@kasparsd what I was reporting is a small typo on the README file, nothing related to the code.

![image](https://user-images.githubusercontent.com/804109/122437933-2dfc7400-cf68-11eb-9d99-ea418bcb6164.png)

Please see the screenshot above taken from the README file: the file location should be `local/public/wp-cli.yml` and not `local/wp-cli.yml`, just that.

Thank you!

**Comment by kasparsd** [comment]
Fixed in #121.
