### ISSUE TITLE
Update URL on the README (documentation)

### ISSUE THREAD

**Issue by nandotess** [xwp/vip-go-site#120]
On the documentation (Heading "Setup", Item 7), it says **Visit [mail.local.devgo.vip](https://local.devgo.vip) to view all emails sent by WordPress**, the URL of the link **mail.local.devgo.vip** is wrong, it's currently pointing to **local.devgo.vip**.

**Comment by nandotess** [comment]
@kasparsd what I was reporting is a small typo on the URL on the README file, nothing related to the code.

![image](https://user-images.githubusercontent.com/804109/122437692-f097e680-cf67-11eb-989d-1b75cb553666.png)

If you click this link above, you go to https://local.devgo.vip/ and not https://mail.local.devgo.vip/. It's a small fix to the documentation that needs to happen, just that.

Thank you!

**Comment by kasparsd** [comment]
Thanks for the clarification @nandotess! And sorry for misunderstanding!
