### ISSUE TITLE
Issue with MySQL on M1 Mac

### ISSUE THREAD

**Issue by m-muhsin** [xwp/vip-go-site#140]
When I start the docker instance using the docker-compose up --detach --remove-orphans --build command, I get this error:

ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries```

This is due to an issue with MySQL not being supported on M1 processors by default.

**Comment by m-muhsin** [comment]
The issue is because of MySQL not supporting M1 architecture by default. https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8/65592942#65592942

**Comment by kasparsd** [comment]
Thanks for reporting the issue @m-muhsin! Will you be able to create a pull request that replaces all references to `mysql:5.7` in `docker-compose.yml` with MariaDB image per https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/
