### ISSUE TITLE
Exclude /local in phpcs.xml

### ISSUE THREAD

**Issue by edmundcwm** [xwp/vip-go-site#54]
Hello @kasparsd !

Since the `local` folder contains the default WP installation, should we look to exclude it from `phpcs.xml`?

The project I'm working on uses this template but has its own custom `PHPCS` ruleset, which didn't exclude the `local` folder. As a result, the PHP linting took really long. 

It seems unnecessary to sniff Core WP files?

**Comment by kasparsd** [comment]
@edmundcwm Thanks for reporting this! 

Could it be that this has changed in one of the recent updates of this library since the exclude file looks like this now:

https://github.com/xwp/vip-go-site/blob/7dd17d16f03b391a833b642da2a5286ce3257298/phpcs.xml.dist#L12-L18

**Comment by kasparsd** [comment]
Closing for now since the current PHPCS config doesn't lint the local folder.
